[package]
name = "metio"
version = "0.1.0"
edition = "2021"
authors = ["Kevin Stiehl <kevin.stiehl@numericas.de>"]
description = "The library for interacting with metio compliant systems"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.190", optional = true}

[features]
serde = ["serde/derive"]
